// PhyriadFG — src/clock/phase_clock.cpp : the STAGE-4 CLOCK, moved VERBATIM out of
// src/present/present.cpp's OUTPUT-CLOCK loop (R1 of docs/planning/CONVERGENCE_MASTER_PLAN.md,
// strategy X14). GENERATED by scratchpad/extract_phase_clock.py from the pre-R1 tree, then kept by
// hand. The bodies are the ORIGINAL LINES: no expression was retyped, re-associated or re-tuned
// (risk XR14 — a 1-ulp shift in t_use is a different presented phase). Each method opens with an
// ALIAS PREAMBLE binding every name the moved body uses (the E1 technique).
//
// DOCUMENTED TRANSFORMS (the complete list; everything else is byte-identical):
//   T1 select(): the line `const double now_d=now_ms();` is dropped — now_d is an input (aliased); the read stays at the call site.
//   T2 select(): `c_slots[rs].t_cap_ms` -> `in.real_tcap(in.real_ctx, rs)` (same value; keeps FgContext/Vulkan out of the CPU-testable unit).
//   T3 select(): `p_presenting.store(fs-gen_back)` moved to the call site (a ring-guard publish, not a clock computation). It now runs BEFORE the gme/bwd/mass reads instead of after — strictly earlier, and those reads do not touch it.
//   T4 order(): `cfg.async_present && async_front>=0` -> the `async_front_ready` parameter (a present-stage fact the clock reads, now declared).
//
// The replay oracle: `phyriad_fg.exe --arrival-log FILE` records this clock's inputs and outputs per
// tick in exact hex-float; tests/clock/test_phase_clock.cpp replays that file through this unit and
// asserts bit-equality (memcmp of the doubles) on every tick.
#include "clock/phase_clock.hpp"
#include <algorithm>
#include <cmath>

namespace pfg::clock {

AdvanceOut PhaseClock::advance(const AdvanceIn& in) {
    // ── alias preamble (the E1 technique): the moved body below is VERBATIM, so every name it uses is
    //    bound here to the member/input that carries it. `now_ms()` is a lambda over the injected read,
    //    `f_seq` a shim with .load() — so the moved lines need no edit and the unit stays deterministic.
    const Cfg&   cfg            = k_;
    const double kScFreqAlpha   = k_.sc_freq_alpha;
    const double kScPhaseGain   = k_.sc_phase_gain;
    const double kScReseatErr   = k_.sc_reseat_err;
    const double tick_period_ms = k_.tick_period_ms;
    const int    NS             = k_.NS;
    const double T_src          = in.T_src;
    const double sc_delta_ms    = in.sc_delta_ms;
    const uint64_t cur_c        = in.cur_c;
    const double now_b          = in.now_b;
    const auto   now_ms         = [&]{ return in.now_b; };
    const struct { uint64_t v; uint64_t load() const { return v; } } f_seq{ in.fs };
    const double*   f_pair_tcap_a = in.ring.tcap;
    const uint64_t* f_pair_span_a = in.ring.span;
    double& content_clock = content_clock_;
    double& T_robust_ms   = T_robust_ms_;
    (void)cfg; (void)tick_period_ms; (void)NS; (void)T_src; (void)sc_delta_ms; (void)cur_c; (void)now_b;

                    // ── sync-clock FREQUENCY loop + NCO advance (armed only) ──
                    // The proportional-FREQUENCY term of the PLL: T_robust tracks the source period via a
                    // SLOW EMA over the outlier-rejected deltas (kScFreqAlpha), so per-frame arrival jitter
                    // barely moves it. Then the NCO accumulator advances by Δ = tick_period_ms / T_robust this
                    // tick — the fractional remainder of the non-integer ticks/source-frame ratio is carried
                    // by the double, NOT re-snapped (the whole fix). Seeded from T_src (the existing EMA) so
                    // the loop starts near-locked. The per-arrival PHASE slew lives in step 3 (needs cur_c/D).
                    if(cfg.sync_clock){
                        if(T_robust_ms<=0.0) T_robust_ms = (T_src>0.0?T_src:tick_period_ms);   // seed
                        if(sc_delta_ms>0.0)  T_robust_ms = T_robust_ms*(1.0-kScFreqAlpha) + sc_delta_ms*kScFreqAlpha;
                        if(T_robust_ms<1e-3) T_robust_ms=1e-3;                                  // guard /0
                        if(sc_init)          content_clock += tick_period_ms / T_robust_ms;     // NCO increment Δ
                    }

                    // ── 3. select the published set whose window contains t_display ─
                    // (cur_c ya leído arriba en el gate del delta — la misma snapshot del tick.)
                    // (R1) the set-detect clock read, HOISTED to one per-tick read so the arrival-log can
                    // record it and PhaseClock can replay it deterministically (documented transform).

                    const uint64_t fs=f_seq.load();
                    const bool have_interp=(fs>=2);
                    // Newest generation (the freshest set F published).
                    const int f_gen_new=have_interp?(int)((fs-1)%(uint64_t)NS):0;
                    // calibrate D = EMA(detect − tcap) over each NEW set, taken
                    // the first tick we observe its f_seq. detect−tcap = publish delay + P's
                    // detection lag; that is exactly the lead a tick must hold so the target
                    // set is fully published when its ticks come due — the tick is a delayed
                    // read of the capture timeline.
                    if(have_interp&&fs!=cur_pair_seq){
                        const double tcap_new=f_pair_tcap_a[f_gen_new];
                        const double det=now_b-tcap_new;                // this set's observed pipeline delay (R1: the hoisted read)
                        if(det>0.0&&det<2000.0){
                            delay_ema_ms=delay_init?delay_ema_ms*0.9+det*0.1:det;
                            freshage_ema_ms=delay_init?freshage_ema_ms*0.9+det*0.1:det;   // same sample, own EMA
                            delay_init=true;
                        }
                        cur_pair_seq=fs;
                    }
                    // D: the calibrated lag the tick reads behind "now". The publish-delay EMA alone
                    // lands t_display right at the freshest set's tcap (phase ≈ 1, which re-presents),
                    // so D adds span so t_display lands inside an already-published set and each tick
                    // walks a distinct pre-generated phase. Cost: lat rises by ~span·T_src. Clamped to a
                    // sane band so a transient publish spike can't run it away.
                    const double span_fresh_ms=have_interp
                        ?(double)std::max<uint64_t>(1,f_pair_span_a[f_gen_new])*T_src : 0.0;
                    // phasefix (default ON): D = freshage_ema + ONE full span, so t_display = now − D lands
                    // at the freshest set's window BOTTOM (tcap_new − span) the tick it publishes (phase 0),
                    // then sweeps to 1 as the ticks walk forward, covering [0,1). freshage_ema is the
                    // detect-time (now − tcap) sample, feedback-free (measured before any D use).
                    // --low-d: a THIRD arm that TRIMS the additive span term (half-span by default + a
                    // lap-escape growth ceiling lowd_span_cap·T_src), with the lower clamp raised to
                    // max(4.0, freshage_ema_ms) so D >= freshage_ema ALWAYS (the freeze floor: a smaller D
                    // selects a FRESHER published pair → the phasefix edge cap below pins it → freeze risk
                    // DROPS, never rises). The other two arms are byte-identical when --low-d is off.
                    const double D = !delay_init ? 0.0
                        : (cfg.phasefix
                             ? (cfg.low_d
                                  ? std::clamp(freshage_ema_ms + std::min(cfg.lowd_span_frac*span_fresh_ms, cfg.lowd_span_cap*T_src),
                                               std::max(4.0, freshage_ema_ms), 250.0)
                                  : std::clamp(freshage_ema_ms + span_fresh_ms, 4.0, 250.0))
                             : std::clamp(delay_ema_ms*1.2 + 0.5*span_fresh_ms, 4.0, 250.0));
                    // ── sync-clock PHASE loop (the proportional-PHASE term; armed only) ──
                    // Runs ONCE per NEW real-pair arrival (cur_c advanced). The expected content position the
                    // free-running clock SHOULD hold = the freshest source index cur_c, set back by the pipeline
                    // lead D expressed in SOURCE-FRAMES (D/T_robust) — the same lead the per-pair path bakes into
                    // t_display = now−D, but here it positions a clock instead of snapping one. err is the phase
                    // discrepancy in source-frames; we SLEW content_clock by a small fraction (kScPhaseGain) of
                    // it — a gentle lock over several arrivals, NEVER the hard per-pair jump. A large err means
                    // lost lock (cut / stall / startup) → re-seat outright (the acquisition path, rare). The NCO
                    // (step 2) keeps advancing between arrivals; this only nudges, so the clock stays MONOTONE in
                    // steady state (a correction never exceeds the accumulated advance for bounded jitter).
                    if(cfg.sync_clock){
                        // reuse cur_c (the single c_seq snapshot read in step 3) — one consistent read per tick.
                        const double lead_frames = (T_robust_ms>1e-3 ? D/T_robust_ms : 0.0);
                        // --vblend-exact: track ~1 pair further back so the selector picks gen_back>=1
                        // and the next-fresher published pair (the EXACT lookahead target) is in the F->P ring.
                        // OFF → −0 → byte-identical (the predict path).
                        // --predict: the MIRROR of vblend-exact — lead the content_clock FORWARD by predict_e
                        // source-frames PAST its normal (interpolating) position so it overshoots the freshest
                        // published pair's endpoint into EXTRAPOLATION (ph>1 → the --asw forward-projection path made
                        // the norm). SOURCE-FRAME units (scale-invariant); the PLL slew/reseat below is UNTOUCHED in
                        // its units — this only shifts the `expected` TARGET the loop chases (err stays steady since
                        // the acquire seeds content_clock=expected). OFF → +0 → byte-identical (the vblend-exact path).
                        // NOTE: NOT `lead_frames + predict_e` — that over-leads (the published pair already trails
                        // cur_c by the pipeline lag, so cancelling lead_frames pushes the clock ~1.5 spans past the
                        // pair endpoint = extrap saturates at asw_max = a constant MAX guess, not a bounded lead;
                        // measured + rejected in PREDICT_MODE_PLAN.md S1). Just +predict_e = a bounded, phase-
                        // continuous overshoot. HONESTY: this re-anchor does NOT reduce the `lat` metric (lat is
                        // freshage-floored, not phase-driven — see PREDICT_MODE_PLAN.md VERDICT + R5); --predict is a
                        // measured NO-GO as a latency feature, kept opt-in + default-OFF only.
                        const double pred_lead = cfg.predict ? (double)cfg.predict_e : 0.0;
                        const double expected = (double)cur_c - lead_frames - (cfg.vblend_exact ? 1.0 : 0.0) + pred_lead;
                        if(!sc_init){
                            content_clock = expected; sc_init=true; sc_last_c=cur_c;   // acquire
                        } else if(cur_c!=sc_last_c){
                            sc_last_c=cur_c;
                            const double err = expected - content_clock;
                            if(std::fabs(err) > kScReseatErr) content_clock = expected;     // re-seat (lost lock)
                            else                              content_clock += kScPhaseGain*err;  // slow slew (locked)
                        }
                    }

    return AdvanceOut{ D, have_interp, f_gen_new, fs };
}

Selection PhaseClock::select(const SelectIn& in) {
    // ── alias preamble (see advance()). The moved body is verbatim; T1..T3 are the only edits.
    const Cfg&   cfg      = k_;
    const int    NS       = k_.NS;
    const int    cap_slots= k_.cap_slots;
    const double T_src    = in.T_src;
    const uint64_t cur_c  = in.cur_c;
    const double D        = in.D;
    const double now_d    = in.now_d;
    const bool   have_interp = in.have_interp;
    const int    f_gen_new   = in.f_gen_new;
    const double*   f_pair_tcap_a = in.ring.tcap;
    const uint64_t* f_pair_cseq_a = in.ring.cseq;
    const uint64_t* f_pair_span_a = in.ring.span;
    const int*      f_pair_n_a    = in.ring.n;
    const int*      f_pair_slot_a = in.ring.slot;
    double& content_clock = content_clock_;
    (void)cfg; (void)NS; (void)cap_slots; (void)T_src; (void)cur_c; (void)D; (void)now_d;

                    // t_display on the capture timeline (tcap shares now_ms()'s steady clock).
                    // Monotone in wall-time: a tick never reads time backwards (the content
                    // monotonicity guard in still protects against content rewind).
                    double t_display=now_d-D;
                    // phasefix: cap t_display to the freshest published edge so a transient that would
                    // push it PAST tcap_new cannot trip the overshoot freeze on a LIVE source (a true stall —
                    // no fresh set arriving — still drains the window and clamps phase to 1, the intended
                    // freeze). Off-fix the cap is absent (byte-identical off pacing).
                    if(cfg.phasefix && have_interp){
                        const double edge=f_pair_tcap_a[f_gen_new];
                        if(edge>0.0 && t_display>edge) t_display=edge;
                    }
                    if(disp_init&&t_display<last_disp_t) t_display=last_disp_t;
                    last_disp_t=t_display; disp_init=true;

                    // Pick the OLDEST live generation whose fresh edge (tcap_r) we have not
                    // yet passed (tcap_r ≥ t_display) — i.e. the earliest set that still
                    // CONTAINS t_display in its window [tcap−span·T, tcap]. Scanning oldest→
                    // newest means phase = the TRUE position of t_display inside that window
                    // and sweeps 0→1 as the tick walks the timeline (the chase-the-newest
                    // selector pinned it near the fresh edge → phase≈0.9 → repeats). If
                    // t_display is past every fresh edge (a real stall, source drained) we
                    // hold the newest and clamps phase to 1 (freeze-at-newest).
                    int f_gen=f_gen_new; int gen_back=0;
                    // `found` lives at this per-tick scope so the --rfp-fresh override gate can REQUIRE it —
                    // the override must NOT fire on the !found deficit-fallback path (which forges
                    // gen_back=0/phase=1.0 below).
                    bool found=false;
                    int    N_set; uint64_t span,pair_c; int rs; double tcap_r;
                    if(have_interp){
                        if(cfg.sc_select && cfg.sync_clock && sc_init){
                            // (fix) content_clock-DRIVEN selection. Selection and the warp
                            // phase now read the SAME clock, so the chosen pair is exactly the one
                            // content_clock is sweeping → phase covers a FULL 0→1 before the pair advances
                            // (no clock-disagreement top truncation / start-stall). Pick the OLDEST published
                            // generation whose B content-index (cand_c) has NOT been passed by content_clock
                            // (cand_c ≥ content_clock) = the pair content_clock currently lies within/before.
                            // SAME loop bounds/order/fallback as the wall-time path → gen_back stays the loop
                            // offset g (p_presenting.store(fs-gen_back) below is preserved). Source-frame
                            // units only (cand_c, content_clock) → scale-invariant.
                            for(int g=NS-1;g>=0;--g){
                                const int cand=(f_gen_new-g+NS*NS)%NS;
                                const double tc=f_pair_tcap_a[cand];
                                const uint64_t cand_c=f_pair_cseq_a[cand];
                                if(tc<=0.0||cand_c==0) continue;          // generation slot never filled
                                if((double)cand_c>=content_clock){ f_gen=cand; gen_back=g; found=true; break; }
                            }
                            // (anti-flap hysteresis) si el pick RETROCEDE respecto al último par PRESENTADO y el
                            // reloj apenas cruzó el límite (dip < kSelHystSrc), mantener la generación más nueva:
                            // el flapeo de borde (slew/jitter del PLL a ±0.1-0.4 src-frames) re-seleccionaba el par
                            // viejo y a fuente rápida (margen D ~2 frames) producía los saltos ±2.0 medidos en el
                            // CSV de cadencia. Un retroceso GENUINO grande (re-seat) supera el umbral y pasa —
                            // el freeze-guard de abajo evita renderizarlo igualmente.
                            constexpr double kSelHystSrc = 0.15;   // src-frames de histéresis anti-flap
                            if(found && have_last_pres && gen_back>0
                               && f_pair_cseq_a[f_gen] < last_pres_cseq
                               && ((double)f_pair_cseq_a[f_gen] - content_clock) < kSelHystSrc){
                                const int cand2=(f_gen_new-(gen_back-1)+NS*NS)%NS;
                                if(f_pair_tcap_a[cand2]>0.0 && f_pair_cseq_a[cand2]!=0){ f_gen=cand2; gen_back=gen_back-1; }
                            }
                        } else {
                            for(int g=NS-1;g>=0;--g){
                                const int cand=(f_gen_new-g+NS*NS)%NS;
                                const double tc=f_pair_tcap_a[cand];
                                if(tc<=0.0) continue;                 // generation slot never filled
                                if(tc>=t_display){ f_gen=cand; gen_back=g; found=true; break; }
                            }
                        }
                        // none contain t_display/content_clock (past all fresh edges) → newest, phase→1.
                        if(!found){ f_gen=f_gen_new; gen_back=0; }
                        N_set  = std::max(1,f_pair_n_a[f_gen]);
                        span   = std::max<uint64_t>(1,f_pair_span_a[f_gen]);
                        pair_c = f_pair_cseq_a[f_gen];
                        rs     = f_pair_slot_a[f_gen];
                        tcap_r = f_pair_tcap_a[f_gen];
                    } else {
                        N_set  = cfg.fg_factor;
                        span   = 1u;
                        pair_c = cur_c;
                        rs     = (int)((cur_c?cur_c-1:0)%(uint64_t)cap_slots);
                        tcap_r = in.real_tcap(in.real_ctx, rs);
                    }
                    // safe-read window: the pair's real slot is valid only while C
                    // has not lapped the ring since F built it.
                    const bool real_valid = !have_interp || ((cur_c-pair_c)<(uint64_t)(cap_slots-1));

                    // ── 4. phase of t_display within the selected set's window ──────
                    // The wall-time map: the pair covers motion over span·T_src,
                    // ending at tcap_r. phase_global ∈ [0,1] across that span.
                    const double span_ms = (double)span*T_src;
                    const double pair_t0 = tcap_r - span_ms;   // wall-time of phase 0
                    // publish the GLOBAL f_seq of the generation we are SAMPLING
                    // (the delayed one fs−gen_back, not the freshest fs) so F's ring guard
                    // stalls before overwriting the generation P actually holds.
                    // t_display before phase 0 (we're holding an older set we haven't reached)
                    // → phase 0; past tcap (the set drained, real stall) → phase 1 freeze.
                    double extrap_amt = 0.0;   // (ASW) forward-extrapolation overshoot (phase units past 1); 0 = none this tick
                    double phase_global = span_ms>1e-6 ? (t_display-pair_t0)/span_ms : 1.0;
                    if(phase_global>1.0){ phase_global=1.0; }
                    if(phase_global<0.0){ phase_global=0.0; }
                    // ── sync-clock phase OVERRIDE (armed only) — the SOLE phase-source swap ──
                    // The per-pair (t_display−pair_t0)/span_ms above EDGE-SNAPS to the jittery arrival timeline
                    // each pair (the boundary judder). When armed, the warp phase is read from the free-running
                    // content_clock instead: phase = (content_clock − (pair_c − span)) / span, clamped [0,1].
                    // • pair_c−span is the content index at phase 0 (the pair's PREV source — same anchor the
                    // per-pair path uses: prev_cseq = pair_c−span below), pair_c is phase 1. Dividing by span
                    // keeps it correct when span>1 (a dropped pair covering span source-frames). SPAN-PACING
                    // is preserved — the content_clock advances across the whole span and the divide maps it.
                    // • clamp [0,1] makes it MONOTONE within the pair and HOLDS at 1.0 if content_clock has run
                    // past pair_c (next pair not ready) — a plain hold, NO extrapolation (the prompt's).
                    // • content_clock only advances, so within a pair phase is monotone by construction; the
                    // existing (pair_c, cand_k) backwards-guard below STILL runs unchanged and still
                    // protects pair-identity / content monotonicity across pairs. Everything downstream
                    // (phase_ms → cand_k → t_use → wap_warp_present AND the --phaselog t_use tap) consumes the
                    // SAME phase_global, so the armed phase flows into the identical call site and the probe.
                    // Scale-invariant: content_clock + span are SOURCE-FRAME units, no panel-rate constant here.
                    if(cfg.sync_clock && sc_init && have_interp && span>=1){
                        const double phase0_c = (double)pair_c - (double)span;     // content index at phase 0
                        double ph = (content_clock - phase0_c) / (double)span;     // [0,1+] across the span
                        if(ph<0.0) ph=0.0;
                        // (ASW) the overshoot past phase 1 = the content_clock ran past the held pair =
                        // B is behind (the deficit/freeze regime). With --asw, instead of HOLD-at-1 (the freeze =
                        // stutter) the warp EXTRAPOLATES the held pair FORWARD by the overshoot (bounded by asw_max):
                        // phase clamps to 1 for the warp's [0,1] math, and the overshoot rides extrap_amt, which the
                        // warp projects as cur[uv-extrap*mv] (the object keeps moving). OFF (--no-asw) or no overshoot
                        // (ph<=1, B keeping up) -> extrap_amt stays 0 -> the plain HOLD-at-1 exactly (byte-identical).
                        if(cfg.asw && ph>1.0){ extrap_amt = ph-1.0; if(extrap_amt>(double)cfg.asw_max) extrap_amt=(double)cfg.asw_max; }
                        if(ph>1.0) ph=1.0;                                         // monotone clamp + plain HOLD at 1 (the non-ASW path)
                        phase_global = ph;
                    }

    return Selection{ t_display, f_gen, gen_back, found, N_set, span, pair_c, rs, tcap_r, real_valid,
                      span_ms, pair_t0, phase_global, extrap_amt };
}

Order PhaseClock::order(double phase_global, double extrap_amt, double span_ms, uint64_t pair_c,
                        bool async_front_ready) {
    // ── alias preamble (see advance()). T4 is the only edit.
    (void)async_front_ready;

                        // Content order key = (pair_c, time-quantised phase to 0.1ms within the
                        // pair window). Monotone forward: never step the phase backwards within a
                        // pair, and never step to an older pair (freeze the held phase instead).
                        // (ASW) add the extrapolation overshoot to the content-order key so each
                        // EXTRAPOLATED tick is DISTINCT content (the object moved) → uniq counts it = the
                        // deficit-fill is MEASURABLE (uniq rises toward panel Hz). extrap_amt=0 when --asw off
                        // or B keeps up → phase_ms unchanged → byte-identical. Monotone: extrap_amt grows while
                        // B is behind, so cand_k advances (no backwards-guard trip); on the next pair pair_c
                        // dominates the order. The warp still gets phase_global∈[0,1] (t_use); only the KEY sees it.
                        const double phase_ms=(phase_global+extrap_amt)*span_ms;   // time into the pair (ASW overshoot)
                        int cand_k=(int)(phase_ms/0.1+0.5);                     // 0.1ms-quantised key
                        bool backwards=false;
                        bool backstep_freeze=false;   // (freeze-guard) tick de par-VIEJO → congelar re-mostrando el front (vía fdrop_this)
                        if(have_last_pres){
                            if(pair_c<last_pres_cseq) backwards=true;
                            else if(pair_c==last_pres_cseq && cand_k<last_pres_k) backwards=true;
                        }
                        double t_use=phase_global;
                        if(backwards){
                            // hold the last shown phase of the held pair (no rewind). If we are on
                            // a NEWER pair than last but it computed an earlier time, clamp to the
                            // start of THIS pair so motion still advances forward in content order.
                            if(pair_c==last_pres_cseq){ cand_k=last_pres_k; t_use=(span_ms>1e-6)?((double)cand_k*0.1/span_ms):phase_global; }
                            else {
                                // (freeze-guard WAP — el fix que el path grid ya tenía y el vivo NO) un tick que
                                // seleccionó un par MÁS VIEJO que el último presentado NUNCA debe renderizarse:
                                // el path viejo lo presentaba a su fase del reloj y el bookkeeping rebobinaba
                                // last_pres → el retroceso llegaba al panel (medido: saltos de −2.0 src-frames en
                                // el CSV de cadencia). Con front async completado → congelar vía el path fdrop
                                // (do_warp=false, re-show del front, bookkeeping intacto). Sin front (arranque) o
                                // en el path síncrono se conserva el comportamiento anterior.
                                if(async_front_ready) backstep_freeze=true;
                                t_use=phase_global;
                            }
                            if(t_use<0.0) t_use=0.0; if(t_use>1.0) t_use=1.0;
                        }

    return Order{ t_use, cand_k, backwards, backstep_freeze };
}

}  // namespace pfg::clock

// Made with my soul - Swately <3
