#pragma once
// PhyriadFG — src/layers/layer_config.hpp : the registry's runtime surface (stage R0).
//   LayerConfig        — the PARSED enables + param values, one storage slot per row/param, defaults
//                        from the tables. Generated by the X-macro tables, never hand-listed.
//   LayerOldShadow     — the pre-cascade snapshot of the hand-parsed Config fields the registry
//                        shadows (captured inside parse_args() right before resolve_config()).
//   layer_shadow_parse — the registry's parser, run as a SHADOW of the hand chain (peeks, never consumes).
//   layer_config_parity— the R0 oracle: the two stores agree on every effective value (risk XR2/XR6).
//   print_layer_help / emit_layer_model_json / layer_dump / layer_contract_hash — the four derived
//                        surfaces (help, UI model, the resolved chain, the FNV-1a contract hash).
// Definitions: src/layers/layer_registry.cpp.
#include "layers/layer_table.hpp"

struct Config;   // cli/cli.hpp (the host struct; it embeds LayerConfig + LayerOldShadow)

namespace pfg::layers {

struct LayerConfig {
    bool  on[kLayerCount];
    float val[kParamCount == 0 ? 1 : kParamCount];   // I32 / BOOL stored as integral floats
    // R5 step 3b — the RESOLVED state, computed once at init by layer_resolve_effective() (bit = layer id):
    //   avail: on && not unavailable && every `needs` row avail (transitive; req_any = any) — "wanted and its inputs exist"
    //   eff:   avail && no `excludes` row avail — the row's call happens. (gme: avail = the model exists, eff = the CPU
    //          variant runs; gme_gpu's eff = the device variant runs.) The FLOW rows on F read these.
    uint32_t avail = 0, eff = 0;
    LayerConfig();                                    // defaults from kLayers / kParams
};

struct LayerOldShadow {
    bool  valid = false;
    bool  mv_guided = false;   float mv_sim = 0.f;
    int   mv_edge_snap = 0;    float mv_edge_snap_sim = 0.f;
    bool  inertia = false;     float inertia_thresh = 0.f;
    float bg_reclaim = 0.f;
    bool  phase_anchor = false;
    bool  ambig = false;
    bool  vblend = false;      float vblend_t0 = 0.f, vblend_strength = 0.f; bool vblend_exact = false;
    bool  stasis = false;      float stasis_thresh = 0.f;
    bool  single_track = false; bool st_no_stasis = false;
    // R5: the FLOW rows' hand fields
    bool  gme = false, gme_gpu = false, gme_gpu_verify = false, gme_irls2 = false;
    bool  objects = false, shapefield = false, obj_fill_rim = false, expire = false, persist_reset = false;
    bool  scene_memory = false, bidir = false, mv_median = false, nvofa = false, mv_consensus = false;
    float mv_smooth = 0.f;
};

// Called at the top of parse_args()'s loop for argv[i]. Peeks argv[i+1] when the token takes a
// value; NEVER modifies i (the hand parser consumes). Returns true if the token is a registry token.
bool layer_shadow_parse(int argc, char** argv, int i, LayerConfig& lc);
// Snapshot of the hand-parsed fields, PRE-cascade (parse_args() calls it before resolve_config()).
LayerOldShadow capture_layer_old(const Config& c);
// The R0 oracle. Prints one "[layertab] PARITY FAIL ..." line per mismatch; false if any.
bool layer_config_parity(const Config& c);

void     print_layer_help();
void     emit_layer_model_json(const Config& c);
void     layer_dump(const Config& c);
void     dump_config(const Config& c);           // --dump-config: the round-trip corpus record
uint64_t layer_contract_hash(const Config& c);

// R3 (stage 5): the host-side halves of the shaders/fg_core.comp contract.
//   layer_params_bytes/fill — the LayerParams UBO bytes (kParams order, 4 B each; I32/BOOL as integers) from the
//                             resolved LayerConfig. clean_sim=false reproduces the legacy's PACKED mv_guided band
//                             ((1 + sim) - 1, wap_warp.comp:325) so M4 byte-identity is provable first (XR1); the
//                             mv_edge_snap "0 = use --mv-sim" cascade is resolved here (no cross-row shader read).
//   layer_arm_mask          — the per-generation row validity (bit = layer id) from the contract's ArmInputs
//                             (STAGE_CONTRACT §1); switches over every ArmId, so a future arm=COMMIT row is armed by
//                             its input, never silently disarmed.
size_t   layer_params_bytes();
void     layer_params_fill(const Config& c, void* out, bool clean_sim);
uint32_t layer_arm_mask(const ArmInputs& in);

// R5 step 3b: resolve avail / eff (above) from the raw enables and the init-time unavailable mask (rows whose
// create-time precondition failed: no WAP → every FLOW row; gme_gpu forced off; a pipe / bridge that failed).
void     layer_resolve_effective(LayerConfig& lc, uint32_t unavailable);
// The FLOW parity: the resolved rows must equal the init cascades' use_* facts (the proof that the rows' declared
// relations reproduce resolve_config / flow_init). Prints "[layertab] FLOW PARITY FAIL ..." per mismatch; false if any.
// Computes the unavailable mask from the facts, resolves, checks, prints the resolved FLOW line once.
bool     layer_flow_resolve(Config& c, bool use_wap, bool use_gme, bool use_gme_gpu, bool use_objects, bool use_memory,
                            bool use_bidir, bool use_ambig, bool use_inertia, bool use_mv_smooth);
// R5 step 4: the union of writes_ch over the effectively-on HOST rows (Kind::H) — the channels a CPU pass dirties,
// so their host copy is authoritative and must be transported back to stage 5. Every other transported channel is
// GPU-produced and GPU-consumed: a device-resident FlowSet could share it without the round trip. Printing this is
// the honest form of the plan's "wap_upload conditional" — the measurement that would justify the data-path change.
uint32_t layer_host_written_channels(const LayerConfig& lc);
void     layer_transport_report(const LayerConfig& lc, uint32_t transported_ch);
// Execution order: (stage, rank) ascending; fills out[0..kLayerCount).
void layer_exec_order(uint16_t out[kLayerCount]);

}  // namespace pfg::layers

// Made with my soul - Swately <3
