#pragma once
// PhyriadFG — src/layers/layer_config.hpp : the registry's runtime surface (stage R0).
//   LayerConfig        — the PARSED enables + param values, one storage slot per row/param, defaults
//                        from the tables. Generated by the X-macro tables, never hand-listed.
//   LayerOldShadow     — the pre-cascade snapshot of the hand-parsed Config fields the registry
//                        shadows (captured inside parse_args() right before resolve_config()).
//   layer_shadow_parse — the registry's parser, run as a SHADOW of the hand chain (peeks, never consumes).
//   layer_config_parity— the R0 oracle: the two stores agree on every effective value (risk XR2/XR6).
//   print_layer_help / emit_layer_model_json / layer_dump / layer_contract_hash — the four derived
//                        surfaces (help, UI model, the resolved chain, the FNV-1a contract hash).
// Definitions: src/layers/layer_registry.cpp.
#include "layers/layer_table.hpp"

struct Config;   // cli/cli.hpp (the host struct; it embeds LayerConfig + LayerOldShadow)

namespace pfg::layers {

struct LayerConfig {
    bool  on[kLayerCount];
    float val[kParamCount == 0 ? 1 : kParamCount];   // I32 / BOOL stored as integral floats
    LayerConfig();                                    // defaults from kLayers / kParams
};

struct LayerOldShadow {
    bool  valid = false;
    bool  mv_guided = false;   float mv_sim = 0.f;
    int   mv_edge_snap = 0;    float mv_edge_snap_sim = 0.f;
    bool  inertia = false;     float inertia_thresh = 0.f;
    float bg_reclaim = 0.f;
    bool  phase_anchor = false;
    bool  ambig = false;
    bool  vblend = false;      float vblend_t0 = 0.f, vblend_strength = 0.f; bool vblend_exact = false;
    bool  stasis = false;      float stasis_thresh = 0.f;
    bool  single_track = false; bool st_no_stasis = false;
};

// Called at the top of parse_args()'s loop for argv[i]. Peeks argv[i+1] when the token takes a
// value; NEVER modifies i (the hand parser consumes). Returns true if the token is a registry token.
bool layer_shadow_parse(int argc, char** argv, int i, LayerConfig& lc);
// Snapshot of the hand-parsed fields, PRE-cascade (parse_args() calls it before resolve_config()).
LayerOldShadow capture_layer_old(const Config& c);
// The R0 oracle. Prints one "[layertab] PARITY FAIL ..." line per mismatch; false if any.
bool layer_config_parity(const Config& c);

void     print_layer_help();
void     emit_layer_model_json(const Config& c);
void     layer_dump(const Config& c);
void     dump_config(const Config& c);           // --dump-config: the round-trip corpus record
uint64_t layer_contract_hash(const Config& c);

// R3 (stage 5): the host-side halves of the shaders/fg_core.comp contract.
//   layer_params_bytes/fill — the LayerParams UBO bytes (kParams order, 4 B each; I32/BOOL as integers) from the
//                             resolved LayerConfig. clean_sim=false reproduces the legacy's PACKED mv_guided band
//                             ((1 + sim) - 1, wap_warp.comp:325) so M4 byte-identity is provable first (XR1); the
//                             mv_edge_snap "0 = use --mv-sim" cascade is resolved here (no cross-row shader read).
//   layer_arm_mask          — the per-generation row validity (bit = layer id) from the contract's ArmInputs
//                             (STAGE_CONTRACT §1); switches over every ArmId, so a future arm=COMMIT row is armed by
//                             its input, never silently disarmed.
size_t   layer_params_bytes();
void     layer_params_fill(const Config& c, void* out, bool clean_sim);
uint32_t layer_arm_mask(const ArmInputs& in);

// Execution order: (stage, rank) ascending; fills out[0..kLayerCount).
void layer_exec_order(uint16_t out[kLayerCount]);

}  // namespace pfg::layers

// Made with my soul - Swately <3
