// PhyriadFG — tools/layer_gen.cpp : the build-time GLSL/offset generator of the layer registry.
//
// A tiny host tool built from the SAME X-macro tables (layers/layer_table.hpp) — not a CMake string
// parser, not Python: it cannot drift from the schema because it IS the schema, compiled. Deviation
// from Candidate C §1.1 (`tools/gen_layer_glsl.cmake`), recorded in the R0 stage record: C itself
// offered a stdlib-Python alternative; a C++ generator from the expanded tables is stronger.
//
// Usage: layer_gen <out_dir>   → writes into <out_dir>:
//   layer_specconst.glsl   layout(constant_id = <id>) const bool L_<NAME> = false;   per real row
//   layer_params.glsl      std140 uniform LayerParams { ... } lp;  + per-row #define aliases
//   layer_includes.glsl    #include "layers/<name>.glsl"  per fused row, rank-ordered
//   chain_mvcond.glsl / chain_sample.glsl / chain_compose.glsl   the ranked call chains
//   layer_offsets.hpp      PFG_OFF_<LAYER>_<PARAM> byte offsets (std140 scalars: 4 * index) + the size
//   layer_manifest.txt     a human listing (rows, ranks, params) — also the DEPENDS witness
// Stage R0: these files are GENERATED but nothing includes them yet (shaders/fg_core.comp is R3).
#include "layers/layer_table.hpp"
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>
#include <algorithm>
#include <cctype>

using namespace pfg::layers;

static std::string upper(const char* s) { std::string r = s; for (auto& ch : r) ch = (char)std::toupper((unsigned char)ch); return r; }

static FILE* open_out(const std::string& dir, const char* name) {
    const std::string p = dir + "/" + name;
    FILE* f = std::fopen(p.c_str(), "wb");
    if (!f) { std::fprintf(stderr, "layer_gen: cannot write %s\n", p.c_str()); std::exit(2); }
    std::fprintf(f, "// GENERATED by tools/layer_gen.cpp from src/layers/layer_table.def — DO NOT EDIT\n");
    return f;
}

int main(int argc, char** argv) {
    if (argc < 2) { std::fprintf(stderr, "usage: layer_gen <out_dir>\n"); return 1; }
    const std::string dir = argv[1];
    std::vector<uint16_t> order(kLayerCount);
    for (uint16_t i = 0; i < kLayerCount; ++i) order[i] = i;
    std::sort(order.begin(), order.end(), [](uint16_t a, uint16_t b) {
        if (kLayers[a].stage != kLayers[b].stage) return (uint8_t)kLayers[a].stage < (uint8_t)kLayers[b].stage;
        return kLayers[a].rank < kLayers[b].rank; });

    // 1. specialization constants
    { FILE* f = open_out(dir, "layer_specconst.glsl");
      for (uint16_t k : order) { const LayerDesc& L = kLayers[k]; if (L.kind == Kind::X) continue;
          std::fprintf(f, "layout(constant_id = %u) const bool L_%s = %s;\n", (unsigned)L.id, upper(L.name).c_str(), L.default_on ? "true" : "false"); }
      std::fclose(f); }

    // 2. the params UBO (std140, scalars only → 4-byte slots) + aliases
    { FILE* f = open_out(dir, "layer_params.glsl");
      std::fprintf(f, "layout(set = 0, binding = 15, std140) uniform LayerParams {\n");
      for (size_t p = 0; p < kParamCount; ++p) {
          const ParamDesc& P = kParams[p];
          const char* ty = P.type == ParamType::F32 ? "float" : (P.type == ParamType::I32 ? "int" : "uint");
          std::fprintf(f, "    %-5s %s_%s;   // offset %zu\n", ty, kLayers[P.layer].name, P.name, p * 4); }
      std::fprintf(f, "} lp;\n");
      for (size_t p = 0; p < kParamCount; ++p) {
          const ParamDesc& P = kParams[p];
          std::fprintf(f, "#define %s_%s lp.%s_%s\n", upper(kLayers[P.layer].name).c_str(), P.name, kLayers[P.layer].name, P.name); }
      std::fclose(f); }

    // 3. includes (fused rows only)
    { FILE* f = open_out(dir, "layer_includes.glsl");
      for (uint16_t k : order) { const LayerDesc& L = kLayers[k]; if (L.kind != Kind::F) continue;
          std::fprintf(f, "#include \"layers/%s.glsl\"\n", L.name); }
      std::fclose(f); }

    // 4. the chains
    auto arm_expr = [](const LayerDesc& L) -> std::string {
        std::string e = "L_" + upper(L.name);
        if (L.arm != ArmId::ALWAYS) e += " && ((pc.arm_mask & (1u << " + std::to_string(L.id) + "u)) != 0u)";
        for (uint16_t j = 0; j < kLayerCount; ++j) if (L.excludes & (1u << j)) e += " && !L_" + upper(kLayers[j].name);
        if (L.needs) {
            std::string r; bool first = true;
            for (uint16_t j = 0; j < kLayerCount; ++j) if (L.needs & (1u << j)) { r += (first ? "" : (L.req_any ? " || " : " && ")); r += "L_" + upper(kLayers[j].name); first = false; }
            e += " && (" + r + ")";
        }
        return e;
    };
    { FILE* f = open_out(dir, "chain_mvcond.glsl");
      std::fprintf(f, "// MVCOND chain: vec2 mv, LayerCtx ctx (ctx.mv_raw_fwd / ctx.sad / ctx.stasis_block written by pseudo-rows)\n");
      for (uint16_t k : order) { const LayerDesc& L = kLayers[k]; if (L.stage != Stage::MVCOND) continue;
          if (L.kind == Kind::X) { std::fprintf(f, "    /* rank %u %s */ %s\n", (unsigned)L.rank, L.name, L.help); continue; }
          if (L.kind == Kind::P) { std::fprintf(f, "    /* rank %u %s: kind=P (an SG pass; not in the fused chain) */\n", (unsigned)L.rank, L.name); continue; }
          if (L.rank == 0) std::fprintf(f, "    vec2 mv = pfg_mvcond_%s(vec2(0.0), ctx);   /* rank 0: the mv-source */\n", L.name);
          else std::fprintf(f, "    if (%s) mv = pfg_mvcond_%s(mv, ctx);   /* rank %u */\n", arm_expr(L).c_str(), L.name, (unsigned)L.rank); }
      std::fclose(f); }
    { FILE* f = open_out(dir, "chain_sample.glsl");
      std::fprintf(f, "    vec2 mv_s = mv;\n");
      for (uint16_t k : order) { const LayerDesc& L = kLayers[k]; if (L.stage != Stage::SAMPLE || L.kind != Kind::F) continue;
          std::fprintf(f, "    if (%s) mv_s = pfg_sample_%s(mv_s, ctx);   /* rank %u */\n", arm_expr(L).c_str(), L.name, (unsigned)L.rank); }
      std::fclose(f); }
    { FILE* f = open_out(dir, "chain_compose.glsl");
      std::fprintf(f, "    vec4 c_out = core.color;   /* the ONLY store source (G1): every COMPOSE row is vec4 f(c_in, ctx) */\n");
      for (uint16_t k : order) { const LayerDesc& L = kLayers[k]; if (L.stage != Stage::COMPOSE || L.kind != Kind::F) continue;
          std::fprintf(f, "    if (%s) c_out = pfg_compose_%s(c_out, ctx);   /* rank %u%s */\n", arm_expr(L).c_str(), L.name, (unsigned)L.rank, L.overrides ? " OVERRIDE" : ""); }
      std::fclose(f); }

    // 5. offsets header
    { FILE* f = open_out(dir, "layer_offsets.hpp");
      std::fprintf(f, "#pragma once\n");
      for (size_t p = 0; p < kParamCount; ++p)
          std::fprintf(f, "#define PFG_OFF_%s_%s %zu\n", upper(kLayers[kParams[p].layer].name).c_str(), upper(kParams[p].name).c_str(), p * 4);
      std::fprintf(f, "#define PFG_LAYER_PARAMS_BYTES %zu\n#define PFG_LAYER_PARAMS_BLOCK %zu\n", kParamCount * 4, ((kParamCount * 4 + 15) / 16) * 16);
      std::fclose(f); }

    // 6. manifest
    { FILE* f = open_out(dir, "layer_manifest.txt");
      std::fprintf(f, "rows=%u params=%zu\n", (unsigned)kLayerCount, (size_t)kParamCount);
      for (uint16_t k : order) { const LayerDesc& L = kLayers[k];
          std::fprintf(f, "%-8s %4u %-18s %c default=%d overrides=%d arm=%s params=%u\n", stage_name(L.stage), (unsigned)L.rank, L.name, kind_char(L.kind), (int)L.default_on, (int)L.overrides, arm_name(L.arm), (unsigned)L.param_count); }
      std::fclose(f); }
    std::printf("layer_gen: %u rows, %zu params -> %s\n", (unsigned)kLayerCount, (size_t)kParamCount, dir.c_str());
    return 0;
}

// Made with my soul - Swately <3
