# framework/render/vulkan/cmake/spv_to_header.cmake
# Convert a SPIR-V binary into a C++ header with the bytecode embedded
# as a `constexpr std::array<uint32_t, N>`. Used by the shader compile
# rule for FrameInterpolatorNode + future v1.1 compute passes.
#
# Invoked via:
#   cmake -D INPUT=foo.spv -D OUTPUT=foo_spv.hpp -D VARNAME=kFooSpv
#         -P spv_to_header.cmake
#
# Output format (deterministic, valid C++23):
#
#   #pragma once
#   #include <array>
#   #include <cstdint>
#   inline constexpr std::array<uint32_t, N> kFooSpv = {
#       0x07230203u, ...
#   };

if(NOT INPUT OR NOT OUTPUT OR NOT VARNAME)
    message(FATAL_ERROR "spv_to_header: requires INPUT, OUTPUT, VARNAME")
endif()

file(READ "${INPUT}" _hex HEX)

# Length in bytes; SPIR-V words are 4 bytes each.
string(LENGTH "${_hex}" _hex_chars)
math(EXPR _byte_count "${_hex_chars} / 2")
math(EXPR _word_count "${_byte_count} / 4")
if(_word_count EQUAL 0)
    message(FATAL_ERROR "spv_to_header: ${INPUT} is empty or unreadable")
endif()

# Build the body of the array. Each word is 8 hex chars from the file
# (little-endian on disk), formatted as 0x... with the u suffix.
set(_body "")
set(_idx 0)
math(EXPR _last_idx "${_word_count} - 1")
while(_idx LESS _word_count)
    math(EXPR _byte_offset "${_idx} * 8")  # 8 hex chars per word
    string(SUBSTRING "${_hex}" "${_byte_offset}" 8 _word_hex)
    # SPIR-V on disk is little-endian; CMake gives us the bytes in file
    # order. Reverse the 4 bytes to recover the host-endian uint32_t.
    string(SUBSTRING "${_word_hex}" 0 2 _b0)
    string(SUBSTRING "${_word_hex}" 2 2 _b1)
    string(SUBSTRING "${_word_hex}" 4 2 _b2)
    string(SUBSTRING "${_word_hex}" 6 2 _b3)
    set(_w "${_b3}${_b2}${_b1}${_b0}")
    if(_idx EQUAL _last_idx)
        string(APPEND _body "    0x${_w}u\n")
    else()
        string(APPEND _body "    0x${_w}u,\n")
    endif()
    math(EXPR _idx "${_idx} + 1")
endwhile()

# Compose the header. We use a unique include guard derived from VARNAME
# so multiple shaders in the same TU don't collide.
string(TOUPPER "${VARNAME}_HPP_GUARD" _guard)

file(WRITE "${OUTPUT}"
"// AUTO-GENERATED by spv_to_header.cmake from ${INPUT}.
// Do not edit by hand. Re-run the build to regenerate.
//
// Layout: ${_word_count} SPIR-V words (${_byte_count} bytes) as
// host-endian uint32_t. Pass straight to vkCreateShaderModule via
// VkShaderModuleCreateInfo::pCode + codeSize.

#ifndef ${_guard}
#define ${_guard}

#include <array>
#include <cstdint>

inline constexpr std::array<uint32_t, ${_word_count}> ${VARNAME} = {
${_body}};

#endif  // ${_guard}
")
# Made with my soul - Swately <3
